name: Assignment 2 - Matrix Testing & Conditional Build

on:
  push:
    branches: [main]
    tags:
      - 'v*.*.*'
  pull_request:
  schedule:
    - cron: '0 3 * * *' # nightly at 3 AM UTC
  workflow_dispatch:
    inputs:
      skip_build:
        description: 'Skip the build step for this manual run?'
        required: false
        default: 'false'

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Nightly test against node:current (Docker container)
  nightly-current:
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    container: node:current
    defaults:
      run:
        working-directory: /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}/frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use npm ci
        run: npm ci
      - name: Run Vitest (text summary)
        run: |
          mkdir -p test-results
          npx vitest run --coverage --reporter=text-summary \
            > test-results/nightly-current.txt
      - uses: actions/upload-artifact@v4
        with:
          name: nightly-current-results
          path: frontend/test-results/nightly-current.txt

  # Matrix tests on LTS versions
  test-matrix:
    name: Test on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    strategy:
      fail-fast: true
      matrix:
        node: [16, 18, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - name: Run Vitest with coverage
        run: |
          mkdir -p test-results
          npx vitest run --coverage --reporter=text-summary \
            > test-results/results-${{ matrix.node }}.txt
      - uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.node }}
          path: frontend/test-results/results-${{ matrix.node }}.txt

  # Aggregate, summarize, and enforce coverage
  test-summary-and-coverage:
    runs-on: ubuntu-latest
    needs: test-matrix
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: test-results
      - name: Concatenate matrix results
        run: |
          mkdir -p test-results/summary
          cat test-results/*/results-*.txt > test-results/summary/combined-results.txt || true
      - name: Add summary to Job Summary
        if: always()
        run: |
          echo '# Matrix Test Summary' >> $GITHUB_STEP_SUMMARY
          echo '\n## Combined Results' >> $GITHUB_STEP_SUMMARY
          if [ -f test-results/summary/combined-results.txt ]; then
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat test-results/summary/combined-results.txt >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo '(No results files found)' >> $GITHUB_STEP_SUMMARY
          fi
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-summary
          path: test-results/summary/combined-results.txt
      - name: Aggregate average coverage and enforce threshold
        id: coverage
        run: |
          line_values=$(grep "Lines" test-results/*/results-*.txt | awk '{print $2}' | tr -d '%')
          statement_values=$(grep "Statements" test-results/*/results-*.txt | awk '{print $2}' | tr -d '%')
          func_values=$(grep "Functions" test-results/*/results-*.txt | awk '{print $2}' | tr -d '%')
          branch_values=$(grep "Branches" test-results/*/results-*.txt | awk '{print $2}' | tr -d '%')
          avg() { sum=0; count=0; for v in $@; do sum=$((sum+v)); count=$((count+1)); done; [ $count -eq 0 ] && echo 0 || echo $((sum/count)); }
          coverage=$(( ( $(avg $line_values) + $(avg $statement_values) + $(avg $func_values) + $(avg $branch_values) ) / 4 ))
          echo "coverage=$coverage" >> $GITHUB_OUTPUT
          echo "Coverage summary: $coverage%"
      - name: Fail if coverage < 70
        run: |
          if [ "${{ steps.coverage.outputs.coverage }}" -lt 70 ]; then
            echo '❌ Coverage too low'
            exit 1
          else
            echo '✅ Coverage OK'
          fi

  # Build only after tests+coverage, and only on main or version tags
  build:
    runs-on: ubuntu-latest
    needs: test-summary-and-coverage
    if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')) && (github.event_name != 'workflow_dispatch' || inputs.skip_build != 'true')
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: mkdir -p dist && echo "Build complete" > dist/build.txt
      - uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: frontend/dist/

  # Optional: Deploy to GitHub Pages with manual approval via environment protection
  deploy-pages:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/download-artifact@v4
        with:
          name: build-dist
          path: ./dist
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - uses: actions/deploy-pages@v4
        id: deployment
