name: Matrix Testing & Conditional Build

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      skip-build:
        description: "Skip build step?"
        required: false
        default: "false"
  schedule:
    - cron: "0 0 * * *" # Daily at midnight UTC

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Matrix Testing (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16, 18, 20]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run Tests
        run: |
          mkdir -p ./test-results
          npx vitest run --reporter=default --reporter=json > ./test-results/test-report-${{ matrix.node-version }}.json
        working-directory: ./frontend

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-report-${{ matrix.node-version }}
          path: ./frontend/test-results/

  summary:
    name: Summarize Test Reports
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./all-results

      - name: Merge reports and count tests
        id: merge
        run: |
          jq -s '[.[]]' ./all-results/**/test-report-*.json > merged-report.json
          total_tests=$(jq '[.[].numTotalTests] | add' merged-report.json)
          echo "total_tests=$total_tests" >> $GITHUB_ENV
          echo "total_tests=$total_tests" >> $GITHUB_OUTPUT
          echo "✅ Total Tests Run: $total_tests"

      - uses: actions/upload-artifact@v4
        with:
          name: merged-report
          path: merged-report.json

  check_tests:
    name: Ensure Tests Did Not Decrease
    runs-on: ubuntu-latest
    needs: summary
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: merged-report
          path: ./current-report

      - name: Compare test counts
        run: |
          current=$(jq '[.[].numTotalTests] | add' ./current-report/merged-report.json)
          echo "Current tests: $current"

          # Optionally save last report in artifacts or repo if you want history
          if [ -f ./prev-report/merged-report.json ]; then
            prev=$(jq '[.[].numTotalTests] | add' ./prev-report/merged-report.json)
            echo "Previous tests: $prev"

            if [ "$current" -lt "$prev" ]; then
              echo "❌ Test count decreased! Failing build."
              exit 1
            fi
          else
            echo "ℹ️ No previous report found, skipping comparison."
          fi

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: [test, summary, check_tests]
    if: >
      (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
      && github.event.inputs.skip-build != 'true'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build project
        run: npm run build
        working-directory: ./frontend

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: ./frontend/dist/
