name: Multi-Branch Deployment

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - "**"

jobs:
  ci:
    name: CI - Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./src/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: ./src

      - name: Run Lint
        run: npm run lint
        working-directory: ./src

      - name: Run Tests
        run: npm test -- --ci --reporters=default
        working-directory: ./src

      - name: Upload Artifact (test-report)
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: ./src/test-results/

  deploy_qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/dev'
    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: test-report
          path: ./qa-artifacts/

      - name: Simulate QA Deployment
        run: echo "🚀 Deploying QA environment with test artifacts..."

  deploy_prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: test-report
          path: ./prod-artifacts/

      - name: Simulate Production Deployment
        run: echo "🚀 Deploying Production environment with test artifacts..."

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "✅ Production Deployment Successful"
          to: "waqarahmed7861234@gmail.com"
          from: "waqarahmed7861234@gmail.com"
          body: |
            Hello Waqar,
            
            The Production deployment has been completed successfully. 🚀
          
            Branch: main
            Time: ${{ github.event.head_commit.timestamp }}
            Commit: ${{ github.sha }}